---
- name: 'PHP-FPM: stop service'
  service: name=php5-fpm state=stopped

# This equals
#  shell: sed -i 's/^pm.max_children.*/pm.max_children = '{{ fpm_max_children }}'/' /etc/php5/fpm/pool.d/www.conf
#  shell: sed -i 's/^pm.start_servers.*/pm.start_servers = '{{ fpm_start_servers }}'/' /etc/php5/fpm/pool.d/www.conf
#  shell: sed -i 's/^pm.min_spare_servers.*/pm.min_spare_servers = '{{ fpm_min_spare_servers }}'/' /etc/php5/fpm/pool.d/www.conf
#  shell: sed -i 's/^pm.max_spare_servers.*/pm.max_spare_servers = '{{ fpm_max_spare_servers }}'/' /etc/php5/fpm/pool.d/www.conf
#  shell: sed -i 's/\;pm.max_requests.*/pm.max_requests = '{{ fpm_max_requests }}'/' /etc/php5/fpm/pool.d/www.conf
#  shell: sed -i 's/^listen =.*/listen = \/var\/run\/php5-fpm-www-data.sock/' /etc/php5/fpm/pool.d/www.conf
- name: 'PHP-FPM: Limit FPM processes & change to socket connection for better performance'
  replace:
    dest: /etc/php5/fpm/pool.d/www.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - {
        regexp: "^pm.max_children.*",
        replace: "pm.max_children = {{ fpm_max_children }}"
      }
    - {
        regexp: "^pm.start_servers.*",
        replace: "pm.start_servers = {{ fpm_start_servers }}"
      }
    - {
        regexp: "^pm.min_spare_servers.*",
        replace: "pm.min_spare_servers = {{ fpm_min_spare_servers }}"
      }
    - {
        regexp: "^pm.max_spare_servers.*",
        replace: "pm.max_spare_servers = {{ fpm_max_spare_servers }}"
      }
    - {
        regexp: "\\;pm.max_requests.*",
        replace: "pm.max_requests = {{ fpm_max_requests }}"
      }
    - {
        regexp: "^listen =.*",
        replace: "listen = /var/run/php5-fpm-www-data.sock"
      }

# This equals
#  shell: sed -i 's/^max_execution_time.*/max_execution_time = '{{ php_max_execution_time }}'/' /etc/php5/fpm/php.ini
#  shell: sed -i 's/^memory_limit.*/memory_limit = '{{ php_memory_limit }}'/' /etc/php5/fpm/php.ini
#  shell: sed -i 's/^max_input_time.*/max_input_time = '{{ php_max_input_time }}'/' /etc/php5/fpm/php.ini
#  shell: sed -i 's/^post_max_size.*/post_max_size = '{{ php_post_max_size }}'/' /etc/php5/fpm/php.ini
#  shell: sed -i 's/^upload_max_filesize.*/upload_max_filesize = '{{ php_upload_max_filesize }}'/' /etc/php5/fpm/php.ini
#  shell: sed -i 's/^expose_php.*/expose_php = Off/' /etc/php5/fpm/php.ini
#  shell: sed -i 's/^disable_functions.*/disable_functions = exec,system,passthru,shell_exec,escapeshellarg,escapeshellcmd,proc_close,proc_open,dl,popen,show_source/' /etc/php5/fpm/php.ini
- name: 'PHP-FPM: Tweak php.ini based on input in config.yml'
  replace:
    dest: /etc/php5/fpm/php.ini
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - {
        regexp: "^max_execution_time.*",
        replace: "max_execution_time = {{ php_max_execution_time }}"
      }
    - {
        regexp: "^memory_limit.*",
        replace: "memory_limit = {{ php_memory_limit }}"
      }
    - {
        regexp: "^max_input_time.*",
        replace: "max_input_time = {{ php_max_input_time }}"
      }
    - {
        regexp: "^post_max_size.*",
        replace: "post_max_size = {{ php_post_max_size }}"
      }
    - {
        regexp: "^upload_max_filesize.*",
        replace: "upload_max_filesize = {{ php_upload_max_filesize }}"
      }
    - {
        regexp: "^expose_php.*",
        replace: "expose_php = Off"
      }
    - {
        regexp: "^disable_functions.*",
        replace: "disable_functions = exec,system,passthru,shell_exec,escapeshellarg,escapeshellcmd,proc_close,proc_open,dl,popen,show_source"
      }


- name: 'PHP-FPM: restart service'
  service: name=php5-fpm state=restarted enabled=yes