---
- name: 'Install OpenSSL'
  apt: name=openssl state=latest force=yes

- name: 'Create directory for local SSL certificates'
  file: path=/etc/ssl/localcerts state=directory

- name: 'Generate self-signed SSL certificate'
  command: openssl req -new -x509 -days 3650 -nodes -subj "/C={{ ssl_country }}/ST={{ ssl_state }}/L={{ ssl_city }}/O={{ ssl_company }}/OU={{ ssl_department }}/CN={{ ssl_hostname }}/emailAddress={{ ssl_mail }}" -out /etc/ssl/localcerts/webserver.pem -keyout /etc/ssl/localcerts/webserver.key
  args:
    creates: /etc/ssl/localcerts/webserver.pem

- name: 'Restart nginx to apply settings'
  when: use_nginx
  service: name=nginx state=restarted enabled=yes
- name: 'Restart apache2 to apply settings'
  when: not use_nginx
  service: name=apache2 state=restarted enabled=yes