---
# Installing updates & configuring SSHD / hostname.
- name: 'aptitude safe-upgrade all packages'
  apt: upgrade=safe update_cache=yes force=yes

# This equals
#  shell: sed -i 's/^Port [0-9]*/Port '{{ sshd_port }}'/' /etc/ssh/sshd_config
#  shell: sed -i 's/PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
- name: 'Reconfigure sshd - change port and disable root login'
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {
        regexp: "^Port",
        line: "Port {{ sshd_port }}"
      }
    - {
        regexp: "^PermitRootLogin",
        line: "PermitRootLogin no"
      }

- name: 'Restart ssh service to apply changes'
  service: name=ssh state=restarted

- name: 'Set FQDN'
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ ansible_default_ipv4.address }}.*"
    line: "{{ ansible_default_ipv4.address }} {{ hostname_fqdn }} {{ hostname }}"
    state: present

- name: 'Set Hostname'
  hostname: name="{{ hostname }}"

- name: 'Restart hostname service to apply changes'
  service: name=hostname state=restarted

# This equals
#  shell: sed -i 's/^#net.ipv4.conf.all.accept_source_route = 0/net.ipv4.conf.all.accept_source_route = 0/' /etc/sysctl.conf
#  shell: sed -i 's/^net.ipv4.conf.all.accept_source_route = 1/net.ipv4.conf.all.accept_source_route = 0/' /etc/sysctl.conf
#  shell: sed -i 's/^#net.ipv6.conf.all.accept_source_route = 0/net.ipv6.conf.all.accept_source_route = 0/' /etc/sysctl.conf
#  shell: sed -i 's/^net.ipv6.conf.all.accept_source_route = 1/net.ipv6.conf.all.accept_source_route = 0/' /etc/sysctl.conf
- name: 'Basic hardening of sysctl.conf'
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {
        regexp: "^#net.ipv4.conf.all.accept_source_route = 0",
        line: "net.ipv4.conf.all.accept_source_route = 0"
      }
    - {
        regexp: "^net.ipv4.conf.all.accept_source_route = 1",
        line: "net.ipv4.conf.all.accept_source_route = 0"
      }
    - {
        regexp: "^#net.ipv6.conf.all.accept_source_route = 0",
        line: "net.ipv6.conf.all.accept_source_route = 0"
      }
    - {
        regexp: "^net.ipv6.conf.all.accept_source_route = 1",
        line: "net.ipv6.conf.all.accept_source_route = 0"
      }