---
- name: 'Install Oracle MySQL'
  when: not install_mariadb and not install_percona
  apt: name={{item}} state=latest force=yes
  with_items:
  - mysql-server
  - mysql-client
- name: 'Install MariaDB MySQL'
  when: install_mariadb and not install_percona
  apt: name={{item}} state=latest force=yes
  with_items:
  - mariadb-server
  - mariadb-client
- name: 'Install Percona MySQL'
  when: install_percona and not install_mariadb
  apt: name={{item}} state=latest force=yes
  with_items:
  - percona-server-server-5.5
  - percona-server-client-5.5

# Ansible mysql_secure_installation playbook version
# Re-used from http://injustfiveminutes.com/2014/08/25/ansible-mysql_secure_installation-playbook/
- name: 'delete anonymous MySQL server user for host: "{{ ansible_hostname }}"'
  mysql_user: user="" host="{{ ansible_hostname }}" state="absent"
- name: delete anonymous MySQL server user for localhost
  mysql_user: user="" state="absent"
- name: remove the MySQL test database
  mysql_db: db=test state=absent
# 'localhost' needs to be the last item for idempotency, see
# http://docs.ansible.com/mysql_user_module.html
- name: Change root user password on first run
  mysql_user: login_user=root
              login_password=''
              name=root
              password={{ mysql_root_password }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
    - "{{ hostname }}"
    - 127.0.0.1
    - ::1
    - localhost