---
- name: 'Install PHP5 base packages'
  apt: name={{item}} state=latest force=yes
  with_items:
  - php5-fpm
  - php5-cli
  - php5-common
  - php-apc
  - php5-mysqlnd
  - php5-dev
- name: 'Install PHP5 extra packages'
  apt: name={{item}} state=latest force=yes
  with_items:
  - php5-memcache
  - php5-curl
  - php5-mcrypt
  - php5-xsl
  - php5-gd
  - php5-imagick
  - php5-snmp
  - php5-xmlrpc

- name: 'Restart nginx to apply settings'
  when: use_nginx
  service: name=nginx state=restarted enabled=yes
- name: 'Restart apache2 to apply settings'
  when: not use_nginx
  service: name=apache2 state=restarted enabled=yes
